import { extendTailwindMerge } from "tailwind-merge";

export const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      color: [
        "common-100",
        "primary",
        "primary-sub-1",
        "primary-sub-2",
        "label-normal",
        "label-strong",
        "label-neutral",
        "label-alternative",
        "label-assistive",
        "label-disable",
        "label-inverse",
        "background-normal",
        "background-alternative",
        "interaction-inactive",
        "interaction-disable",
        "line-normal",
        "line-neutral",
        "line-alternative",
        "status-success",
        "status-error",
        "status-informative",
        "accent-red-orange",
        "accent-cyan",
        "accent-light-blue",
        "accent-violet",
        "accent-purple",
        "accent-pink",
        "component-fill-normal",
        "component-fill-strong",
        "component-fill-alternative",
        "component-fill-neutral",
      ],
      text: [
        "display-1",
        "display-2",
        "title-1",
        "title-2",
        "title-3",
        "heading-1",
        "headline-1",
        "body-1-normal",
        "body-1-reading",
        "body-2-normal",
        "body-2-reading",
        "label-1-normal",
        "label-1-reading",
        "caption-1",
        "caption-2",
      ],
      radius: ["4", "8"],
    },
  },
});
